# Generated by Django 4.2.3 on 2023-07-26 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_driver_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyuser',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='user.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verifyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
