# Generated by Django 4.2.3 on 2023-07-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verifyuser_driver_alter_verifyuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyuser',
            name='driver',
        ),
    ]
