# Generated by Django 4.2.3 on 2023-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_verifyuser_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_id',
            field=models.CharField(default='UNIT0001', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='vin_id',
            field=models.CharField(default='VIN0001', max_length=100),
            preserve_default=False,
        ),
    ]
