# Generated by Django 4.2.3 on 2023-07-21 06:11

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default=1, upload_to=file.models.upload),
            preserve_default=False,
        ),
    ]
