# Generated by Django 4.2.3 on 2023-07-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_driver_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('Regulated Hours of Service', 'Hos'), ('Health Issues', 'Health Issues'), ('Family Emergency', 'Family Emergency'), ('Other Reasons', 'Other')], default='Regulated Hours of Service', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometime_requests', to='user.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
