# Generated by Django 4.2.3 on 2023-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('Regulated Hours of Service', 'Hos'), ('Health Related Issues', 'Health Issues'), ('Family Emergency', 'Family Emergency'), ('Other Reasons', 'Other')], default='Regulated Hours of Service', max_length=255)),
                ('status', models.CharField(choices=[('Waiting for Approval', 'Waiting For Approval'), ('Approved', 'Approved')], default='Waiting for Approval', max_length=50)),
                ('location_by_state', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=25)),
                ('latitude', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
