# Generated by Django 4.2.3 on 2023-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometime',
            name='location',
        ),
        migrations.AddField(
            model_name='hometime',
            name='latitude',
            field=models.CharField(default='40.2361', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometime',
            name='longitude',
            field=models.CharField(default='65.2341', max_length=25),
            preserve_default=False,
        ),
    ]
