# Generated by Django 4.2.3 on 2023-07-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometime',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hometime',
            name='longitude',
        ),
    ]
