# Generated by Django 4.2.3 on 2023-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0002_remove_hometime_location_hometime_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometime',
            name='location_by_state',
            field=models.CharField(default='Ohio, Cleveland', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hometime',
            name='reason',
            field=models.CharField(choices=[('Regulated Hours of Service', 'Hos'), ('Health Related Issues', 'Health Issues'), ('Family Emergency', 'Family Emergency'), ('Other Reasons', 'Other')], default='Regulated Hours of Service', max_length=255),
        ),
    ]
