# Generated by Django 4.2.3 on 2023-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer_id', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('issue', models.CharField(choices=[('faulty lighting issue', 'Faulty Lighing Issue'), ('trailer coupling failure', 'Trailer Coupling Failure'), ('cargo securement issue', 'Cargo Securement Issue'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'verbose_name': 'Trailer Issue',
                'verbose_name_plural': 'Trailer Issues',
            },
        ),
        migrations.CreateModel(
            name='TruckIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_id', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('issue', models.CharField(choices=[('electrical issue', 'Electrical Issue'), ('fuel related issue', 'Fuel Related Issue'), ('cooling system issue', 'Cooling System Issue'), ('brake system issue', 'Brake System Issue'), ('steering and suspension issue', 'Steering And Suspension Issue'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'verbose_name': 'Truck Issue',
                'verbose_name_plural': 'Truck Issues',
            },
        ),
    ]
