# Generated by Django 4.2.3 on 2023-07-18 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailerissue',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trailerissue',
            name='trailer_id',
        ),
        migrations.RemoveField(
            model_name='truckissue',
            name='model',
        ),
        migrations.RemoveField(
            model_name='truckissue',
            name='truck_id',
        ),
        migrations.AddField(
            model_name='trailerissue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_issues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truckissue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='truck_issues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
