# Generated by Django 4.2.3 on 2023-07-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckissue',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='truckissue',
            name='photos',
            field=models.ManyToManyField(to='file.file'),
        ),
        migrations.AddField(
            model_name='trailerissue',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trailerissue',
            name='photos',
            field=models.ManyToManyField(to='file.file'),
        ),
    ]
