# Generated by Django 4.2.3 on 2023-08-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('police_involement', models.CharField(choices=[('No involvement of the law enforcement agencies', 'Not Notified'), ('Law enforcement was notified about the accident, but they did not respond to the scene', 'Not Responded'), ('Law enforcement authorities were notified about the accident and responded to the scene', 'Responded'), ('The police are actively investigating the accident', 'Investigation Ongoing'), ('After conducting a thorough investigation, the police have filed an official report detailing the accidents circumstances, parties involved, and their findings.', 'Report Filed'), ('The police have concluded their investigation and given clearance for the involved vehicles to be moved from the accident scene', 'Clearance Given'), ('In cases where the accident was a result of a violation of traffic laws or negligence, the police may file charges against one or more parties involved', 'Charges Filed'), ('The parties involved exchanged information and resolved the situation amicably', 'No Police Needed'), ('The police involvement status is unknown or not disclosed in the available information', 'Unknown')], max_length=255)),
                ('report_status', models.CharField(choices=[('The accident has been reported to the relevant authorities or agency responsible for handling accident reports', 'Reported'), ('The accident report is currently under investigation. This status indicates that authorities are collecting evidence, interviewing witnesses, and analyzing the circumstances of the accident', 'Under Investigation'), ('Investigators are in the process of gathering evidence, such as photographs, videos, witness statements, and other relevant information', 'Evidence Gathering'), ('Authorities are conducting interviews with individuals involved in the accident, including drivers, passengers, and witnesses', 'Interviewing Aprties'), ('The completed accident report is pending review by supervisory personnel or higher-ranking officers before being finalized', 'Pending Reviews'), ('Investigators have determined the primary cause of the accident based on evidence and statements gathered', 'Accident Cause Determined'), ('If applicable, authorities have assigned fault or responsibility to one or more parties involved in the accident', 'Fault Assignement'), ('Law enforcement authorities are considering filing charges against individuals responsible for causing the accident due to violations of traffic laws or negligence', 'Pending Charges'), ('The accident report has been completed, including all necessary details, statements, and evidence. It is now ready for distribution or sharing with relevant parties', 'Report Completed'), ('If an insurance claim is related to the accident, this status indicates that the involved parties have filed their claims with their respective insurance companies', 'Insurance Claim Filed'), ('The case has been resolved through negotiations, settlements, or other means. This status might indicate that the involved parties have agreed on a resolution outside of legal proceedings', 'Resolution Reached'), ('Legal action, such as a lawsuit, has been initiated as a result of the accident. This status indicates that the case has escalated beyond the investigative stage', 'Legal Action Taken'), ('The accident report has been closed, indicating that the investigation and any resulting actions or legal proceedings have been concluded', 'Closed'), ('The accident report has been archived for future reference. This might happen after a certain period of time has passed since the accident', 'Archived'), ('The report is awaiting updates or additional information that may impact the conclusions or actions related to the accident', 'Pending Updates')], max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accident Report',
                'verbose_name_plural': 'Accident Reports',
            },
        ),
    ]
