# Generated by Django 4.2.3 on 2023-07-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_trailerissue_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailerissue',
            old_name='user',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='truckissue',
            old_name='user',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='trailerissue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Fixed', 'Fixed'), ('Not Fixed', 'Not Fixed'), ('Pending Parts', 'Pending Parts'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='truckissue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Fixed', 'Fixed'), ('Not Fixed', 'Not Fixed'), ('Pending Parts', 'Pending Parts'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='trailerissue',
            name='issue',
            field=models.CharField(choices=[('Faulty Lighting Issue', 'Faulty Lighing Issue'), ('Trailer Coupling Failure', 'Trailer Coupling Failure'), ('Cargo Securement', 'Cargo Securement Issue'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='truckissue',
            name='issue',
            field=models.CharField(choices=[('Electrical', 'Electrical Issue'), ('Fuel Related', 'Fuel Related Issue'), ('Cooling System', 'Cooling System Issue'), ('Brake System', 'Brake System Issue'), ('Steering and Suspension', 'Steering And Suspension Issue'), ('Other', 'Other')], max_length=50),
        ),
    ]
