# Generated by Django 4.2.3 on 2023-07-20 07:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('tracking', '0003_photo_alter_truckissue_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos/issues')),
        ),
        migrations.AlterField(
            model_name='truckissue',
            name='photos',
            field=models.ManyToManyField(to='file.file'),
        ),
    ]
