# Generated by Django 4.2.3 on 2023-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('tracking', '0003_rename_user_trailerissue_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerissue',
            name='photos',
            field=models.ManyToManyField(to='file.file'),
        ),
    ]
