# Generated by Django 4.2.3 on 2023-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('tracking', '0004_trailerissue_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckissue',
            name='photos',
            field=models.ManyToManyField(to='file.file'),
        ),
    ]
