# Generated by Django 4.2.3 on 2023-07-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_photo_image_alter_truckissue_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
