# Generated by Django 4.2.3 on 2023-07-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_unit_id_remove_user_vin_id_driver'),
        ('tracking', '0005_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerissue',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_issues', to='user.driver'),
        ),
        migrations.AlterField(
            model_name='truckissue',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_issues', to='user.driver'),
        ),
    ]
